#pragma once

#include "dsl/dsl_base.h"
#include "dsl/to_dsl_trait.h"
#include "dsl/dsl_meta.h"
#include "dsl/cast.h"
#include "dsl/op.h"
#include "dsl/var.h"
#include "dsl/ptr.h"
#include "dsl/array.h"
//#include "dsl/struct.h"
#include "dsl/fun.h"
#include "dsl/ResidentObjCode.h"
#include "dsl/sequence.h"
#include "dsl/if_else.h"
#include "dsl/loops.h"
