LLVM_REL=50
LLVMS_DIR=/home/hades/projects/llvms
BASE_DIR=$LLVMS_DIR/llvm_$LLVM_REL

SRC_DIR=$BASE_DIR/llvm
INSTALL_DIR=$BASE_DIR/install_dir

#GENERATOR="Ninja"
GENERATOR="Unix Makefiles"

cmake -G "$GENERATOR" $SRC_DIR \
    -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
    -DLLVM_TARGETS_TO_BUILD="X86;ARM;MSP430" \
    \
    -DLLVM_ENABLE_THREADS=OFF \
    -DLLVM_USE_LINKER=lld \

    #-DLLVM_INCLUDE_TOOLS=OFF \
    #-DLLVM_BUILD_TOOLS=OFF \
